<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BreedingModLoader.cs" />
    <Compile Include="Breeding/BreedingConfig.cs" />
    <Compile Include="Breeding/BreedingState.cs" />
    <Compile Include="Breeding/SubsystemBreeding.cs" />
    <Compile Include="Breeding/BreedingInfoPanel.cs" />
    <Compile Include="Breeding/InfoLine.cs" />
    <Compile Include="Breeding/InfoLineBuilder.cs" />
    <Compile Include="Breeding/NeorxnaBreedingNui.cs" />
    <Compile Include="Breeding/BreedingDisplaySettings.cs" />
    <Compile Include="Breeding/SubsystemBreedingEggBehavior.cs" />
    <Compile Include="Breeding/BreedingEggManager.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Engine" HintPath="Quoted/Engine.dll" />
    <Reference Include="EntitySystem" HintPath="Quoted/EntitySystem.dll" />
    <Reference Include="Survivalcraft" HintPath="Quoted/Survivalcraft.dll" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Text.Json" />
  </ItemGroup>
  <PropertyGroup>
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <UseMauiEssentials>false</UseMauiEssentials>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>